# Generated by Django 4.2.7 on 2026-07-16 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_alter_staff_biography_alter_staff_display_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='researchers/')),
                ('biography', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('highest_qualification', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('research_interests', models.TextField(blank=True)),
                ('orcid', models.CharField(blank=True, max_length=255)),
                ('google_scholar', models.URLField(blank=True)),
                ('researchgate', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_profile', to='staff.staff')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
                'ordering': ['display_order', 'display_name', 'last_name', 'first_name', 'id'],
            },
        ),
    ]
