# Generated by Django 4.2.7 on 2026-01-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_alter_programme_career_prospects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_number', models.CharField(help_text='Official matriculation number', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Student full name as it appears on records', max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Year of graduation (leave empty for current students)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.programme')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['matriculation_number'], name='students_st_matricu_41b295_idx')],
            },
        ),
    ]
