# Generated by Django 4.2.7 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the student', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ND I', 'National Diploma 100L'), ('ND II', 'National Diploma 200L'), ('PD I', 'Professional Diploma 100L'), ('PD II', 'Professional Diploma 200L'), ('PD III', 'Professional Diploma 300L')], default='ND I', help_text='Academic level for this student', max_length=6),
        ),
    ]
