# Generated by Django 4.2.7 on 2026-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_index_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gsm_number',
            field=models.CharField(blank=True, help_text='Student GSM/mobile number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks about the student', null=True),
        ),
    ]
