# Generated by Django 4.2.7 on 2026-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_gsm_number_student_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('ND I', 'National Diploma 100L'), ('ND II', 'National Diploma 200L'), ('PD I', 'Professional Diploma 100L'), ('PD II', 'Professional Diploma 200L'), ('PD III', 'Professional Diploma 300L'), ('HND I', 'Higher National Diploma 100L'), ('HND II', 'Higher National Diploma 200L')], default='ND I', help_text='Academic level for this student', max_length=6),
        ),
    ]
