# Generated by Django 4.2.7 on 2026-07-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload a PDF, journal, circular or official document.', null=True, upload_to='news/documents/'),
        ),
    ]
