# Generated by Django 4.2.7 on 2026-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this publication has been viewed.'),
        ),
    ]
