# Generated by Django 4.2.7 on 2026-07-15

from django.db import migrations, models
import django.db.models.deletion


def backfill_publication_authors(apps, schema_editor):
    News = apps.get_model("news", "News")
    PublicationAuthor = apps.get_model("news", "PublicationAuthor")

    for news_item in News.objects.select_related("author").all():
        if not news_item.author_id:
            continue

        if PublicationAuthor.objects.filter(publication_id=news_item.pk).exists():
            continue

        PublicationAuthor.objects.create(
            publication_id=news_item.pk,
            staff_id=news_item.author_id,
            external_name=news_item.author.name,
            affiliation=news_item.author.department,
            is_primary=True,
            is_corresponding=True,
            display_order=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_name", models.CharField(max_length=200)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("orcid", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_corresponding", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("publication", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publication_authors", to="news.news")),
                ("staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publication_authorships", to="staff.staff")),
            ],
            options={
                "verbose_name": "Publication Author",
                "verbose_name_plural": "Publication Authors",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationauthor",
            constraint=models.UniqueConstraint(
                fields=("publication",),
                condition=models.Q(is_corresponding=True),
                name="unique_corresponding_author_per_publication",
            ),
        ),
        migrations.RunPython(backfill_publication_authors, migrations.RunPython.noop),
    ]
