# Generated by Django 4.2.7 on 2026-07-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
        ('news', '0007_publicationauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationauthor',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_authorships', to='researchers.researcher'),
        ),
    ]
