# Generated by Django 4.2.7 on 2026-07-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_biography_alter_staff_display_order_and_more'),
        ('news', '0008_publicationauthor_researcher_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Staff member who authored this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary displayed on the news listing page.', max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False, help_text='Display this article in featured sections.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
