# Generated by Django 4.2.7 on 2025-12-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='staff/')),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('qualifications', models.TextField()),
                ('biography', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic Staff'), ('non_academic', 'Non-Academic Staff')], max_length=20)),
            ],
        ),
    ]
