# Generated by Django 5.0.7 on 2025-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (for management staff)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Staff'), ('non_academic', 'Non-Academic Staff'), ('management', 'Management Staff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
