# Generated by Django 4.2.7 on 2026-01-04 12:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_staff_created_at_staff_is_approved_staff_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterField(
            model_name='staff',
            name='biography',
            field=models.TextField(blank=True, help_text='Brief professional biography (optional).'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved staff are visible on the website.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a square image (JPG, PNG, or WEBP). Max size: 2MB.', null=True, upload_to='staff/', validators=[staff.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Academic and professional qualifications.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
