# Generated by Django 4.2.7 on 2026-01-04 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0004_alter_staff_options_alter_staff_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='biography',
            field=models.TextField(blank=True, help_text='Short professional biography (optional)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved staff are visible on the public website'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport photograph (max 2MB, JPG/PNG recommended)', null=True, upload_to='staff/', validators=[staff.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualifications',
            field=models.TextField(help_text='Academic and professional qualifications'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional system user account linked to this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
