# Generated by Django 4.2.7 on 2026-07-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researchers', '0001_initial'),
        ('staff', '0005_alter_staff_biography_alter_staff_display_order_and_more'),
        ('news', '0009_alter_news_author_alter_news_excerpt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('submission_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('funding_information', models.TextField(blank=True)),
                ('ethical_approval', models.TextField(blank=True)),
                ('conflict_of_interest', models.TextField(blank=True)),
                ('acknowledgements', models.TextField(blank=True)),
                ('notes_to_editor', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='news.category')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('file_type', models.CharField(choices=[('main_manuscript', 'Main Manuscript'), ('figures', 'Figures'), ('tables', 'Tables'), ('supplementary_material', 'Supplementary Material'), ('dataset', 'Dataset'), ('ethics_approval', 'Ethics Approval'), ('other', 'Other')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Submission File',
                'verbose_name_plural': 'Submission Files',
                'ordering': ['-uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(max_length=200)),
                ('author_order', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=255)),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_authorships', to='researchers.researcher')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_authorships', to='staff.staff')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='submissions.submission')),
            ],
            options={
                'verbose_name': 'Submission Author',
                'verbose_name_plural': 'Submission Authors',
                'ordering': ['author_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='corresponding_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submissionauthor'),
        ),
    ]
