# Generated by Django 4.2.7 on 2025-12-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'academic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_of', to='staff.staff'),
        ),
    ]
