# Generated by Django 5.0.7 on 2025-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_school_dean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='accredited',
        ),
        migrations.AddField(
            model_name='programme',
            name='career_prospects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='certification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programme',
            name='entry_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.CharField(choices=[('PD', 'Professional Diploma'), ('ND', 'National Diploma'), ('HND', 'Higher National Diploma')], max_length=5),
        ),
    ]
