# Generated by Django 5.0.7 on 2025-12-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_programme_accredited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='career_prospects',
            field=models.TextField(blank=True, help_text='Possible career paths for graduates'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='certification',
            field=models.CharField(blank=True, help_text='Certificate awarded upon successful completion', max_length=200),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(blank=True, help_text='Brief overview of the programme'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2 Years, 3 Years', max_length=100),
        ),
        migrations.AlterField(
            model_name='programme',
            name='entry_requirements',
            field=models.TextField(blank=True, help_text="O'Level subjects, JAMB requirements, or HND conditions"),
        ),
        migrations.AlterField(
            model_name='programme',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='academics.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(help_text='Brief description of the school and its academic focus'),
        ),
    ]
